'use client'

import { useState } from 'react'
import Image from 'next/image'
import { JobReportData } from '@/types/report'
import { ImageModal } from './ImageModal'
import { TeamSignatures } from './TeamSignatures'
import { getEffectivePhotoCategory, type PhotoCategory } from '@/lib/utils/photoCategory'

interface ReportViewProps {
  data: JobReportData
  readOnly?: boolean
  onExport?: () => void
  exportInProgress?: boolean
  /** When provided and not readOnly, enables category edit affordances and PATCH calls */
  onDocumentCategoryChange?: (docId: string, category: PhotoCategory) => Promise<void>
}

function formatName(user: { actor_name?: string | null; actor_email?: string | null } | null): string {
  if (!user) return 'System'
  if (user.actor_name) {
    // Format as "Last, First" if it contains a space
    const parts = user.actor_name.split(' ')
    if (parts.length > 1) {
      return `${parts[parts.length - 1]}, ${parts.slice(0, -1).join(' ')}`
    }
    return user.actor_name
  }
  return user.actor_email || 'Unknown'
}

function formatAuditEntry(log: JobReportData['audit'][0]): string {
  const actor = formatName(log)
  
  switch (log.event_name) {
    case 'job.created':
      return `Job created by ${actor}`
    case 'job.updated':
      return `Job details updated by ${actor}`
    case 'document.uploaded':
      const docName = log.metadata?.name || 'a file'
      return `Document "${docName}" uploaded by ${actor}`
    case 'mitigation.completed':
      return `Mitigation completed by ${actor}`
    case 'mitigation.reopened':
      return `Mitigation reopened by ${actor}`
    case 'report.generated':
      return `Report generated by ${actor}`
    default:
      return `${log.event_name} by ${actor}`
  }
}

function formatTime(dateString: string): string {
  try {
    const date = new Date(dateString)
    return date.toLocaleTimeString('en-US', {
      timeZone: 'America/New_York',
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'short',
    })
  } catch {
    return ''
  }
}

function formatUTCTime(dateString: string): string {
  try {
    const date = new Date(dateString)
    return date.toLocaleTimeString('en-US', {
      timeZone: 'America/New_York',
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
      timeZoneName: 'short',
    })
  } catch {
    return ''
  }
}

function getRiskColor(level: string | null): string {
  if (!level) return 'text-green-400'
  const lower = level.toLowerCase()
  if (lower === 'critical' || lower === 'high') return 'text-red-400'
  if (lower === 'medium') return 'text-yellow-400'
  return 'text-green-400'
}

function getSeverityColor(severity: string): string {
  const lower = severity.toLowerCase()
  if (lower === 'critical') return 'bg-red-500/20 text-red-400 border-red-500/30'
  if (lower === 'high') return 'bg-orange-500/20 text-orange-400 border-orange-500/30'
  if (lower === 'medium') return 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30'
  return 'bg-green-500/20 text-green-400 border-green-500/30'
}

export function ReportView({
  data,
  readOnly = false,
  onExport,
  exportInProgress = false,
  onDocumentCategoryChange,
}: ReportViewProps) {
  const { job, risk_score, mitigations, documents, audit, organization } = data

  const completedControls = mitigations.filter(m => m.done || m.is_completed).length
  const totalControls = mitigations.length
  const photos = documents.filter(d => d.type === 'photo' && d.url) as Array<{
    id: string
    name: string
    description?: string | null
    url?: string | null
    created_at?: string | null
    category?: PhotoCategory | null
  }>

  const [selectedImage, setSelectedImage] = useState<{ url: string; alt: string } | null>(null)
  const [photoFilter, setPhotoFilter] = useState<'all' | PhotoCategory>('all')
  const [categoryDropdownOpen, setCategoryDropdownOpen] = useState<string | null>(null)

  const jobStart = job.start_date ?? null
  const jobEnd = job.end_date ?? null
  const effectiveCat = (p: (typeof photos)[number]) =>
    getEffectivePhotoCategory(p, jobStart, jobEnd)
  const filteredPhotos =
    photoFilter === 'all' ? photos : photos.filter((p) => effectiveCat(p) === photoFilter)
  const beforeCount = photos.filter((p) => effectiveCat(p) === 'before').length
  const duringCount = photos.filter((p) => effectiveCat(p) === 'during').length
  const afterCount = photos.filter((p) => effectiveCat(p) === 'after').length
  const categoryBadgeClass = (cat: PhotoCategory) => {
    if (cat === 'before') return 'bg-[#e3f2fd] text-[#1976d2]'
    if (cat === 'after') return 'bg-[#e8f5e9] text-[#388e3c]'
    return 'bg-[#fff3e0] text-[#f57c00]'
  }
  const canEditCategory = !readOnly && !!onDocumentCategoryChange

  // Get most recent audit entry for system timestamp (sorted by created_at descending)
  const sortedAudit = [...audit].sort((a, b) => 
    new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  )
  const lastSystemUpdate = sortedAudit.length > 0 ? sortedAudit[0].created_at : null
  
  // Check if job is archived or completed (for immutable messaging)
  const isArchivedOrCompleted = job.status === 'archived' || job.status === 'completed'

  return (
    <>
      <ImageModal
        isOpen={selectedImage !== null}
        imageUrl={selectedImage?.url || null}
        imageAlt={selectedImage?.alt}
        onClose={() => setSelectedImage(null)}
      />
      <div className="space-y-12">
      {/* Header Section */}
      <div className="space-y-6">
        <div>
          <div className="flex items-start justify-between">
        <div>
          <h1 className="text-4xl font-bold text-white mb-2">{job.job_type}</h1>
          <p className="text-white/60 text-lg">{job.location}</p>
            </div>
            {lastSystemUpdate && (
              <div className="text-right">
                <p className="text-xs text-white/40">
                  Last system update: {formatUTCTime(lastSystemUpdate)}
                </p>
              </div>
            )}
          </div>
          {isArchivedOrCompleted && (
            <p className="text-xs text-white/40 mt-3 italic">
              This page is immutable once archived
            </p>
          )}
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div className="bg-white/5 border border-white/10 rounded-xl p-4">
            <div className="text-2xl font-bold text-white">{risk_score?.factors?.length || 0}</div>
            <div className="text-sm text-white/60">Hazards</div>
          </div>
          <div className="bg-white/5 border border-white/10 rounded-xl p-4">
            <div className="text-2xl font-bold text-white">
              {completedControls}/{totalControls}
            </div>
            <div className="text-sm text-white/60">Controls</div>
          </div>
          <div className="bg-white/5 border border-white/10 rounded-xl p-4">
            <div className="text-2xl font-bold text-white">{photos.length}</div>
            <div className="text-sm text-white/60">Photos</div>
          </div>
          <div className="bg-white/5 border border-white/10 rounded-xl p-4">
            <div className="text-2xl font-bold text-white">{job.status.toUpperCase()}</div>
            <div className="text-sm text-white/60">Status</div>
          </div>
        </div>

        {/* Risk Score */}
        {risk_score && (
          <div className="bg-white/5 border border-white/10 rounded-xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <div className="text-sm text-white/60 mb-1">Risk Score</div>
                <div className={`text-5xl font-bold ${getRiskColor(risk_score.risk_level)}`}>
                  {risk_score.overall_score}
                </div>
                <div className={`text-lg font-semibold mt-2 ${getRiskColor(risk_score.risk_level)}`}>
                  {risk_score.risk_level?.toUpperCase() || 'UNKNOWN'}
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Actions */}
      {!readOnly && (
        <div className="space-y-3">
          <div className="flex gap-3 items-center">
          {onExport && (
            <button
              onClick={onExport}
              disabled={exportInProgress}
              className="rounded-lg bg-[#F97316] px-6 py-3 text-black font-semibold hover:bg-[#FB923C] disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {exportInProgress ? 'Exporting...' : 'Export PDF'}
            </button>
            )}
          </div>
          {onExport && (
            <p className="text-xs text-white/40">
              This view is exportable for audits
            </p>
          )}
        </div>
      )}

      {/* Hazards */}
      {risk_score && risk_score.factors.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-2xl font-bold text-white">⚠️ Hazard Checklist</h2>
          <div className="bg-white/5 border border-white/10 rounded-xl p-6 space-y-3">
            {risk_score.factors.map((factor, idx) => (
              <div key={idx} className="flex items-start justify-between py-3 border-b border-white/5 last:border-0">
                <div className="flex-1">
                  <div className="font-semibold text-white mb-1">{factor.name || factor.code}</div>
                </div>
                <div className={`px-3 py-1 rounded-full text-xs font-semibold border ${getSeverityColor(factor.severity)}`}>
                  {factor.severity.toUpperCase()}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Controls */}
      {mitigations.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-2xl font-bold text-white">🛠️ Controls Applied</h2>
          <div className="bg-white/5 border border-white/10 rounded-xl p-6 space-y-3">
            {mitigations.map((item) => {
              const isCompleted = item.done || item.is_completed
              return (
                <div key={item.id} className="flex items-start gap-3 py-3 border-b border-white/5 last:border-0">
                  <div className={`mt-1 ${isCompleted ? 'text-green-400' : 'text-white/30'}`}>
                    {isCompleted ? '[X]' : '[ ]'}
                  </div>
                  <div className="flex-1">
                    <div className={`font-semibold ${isCompleted ? 'text-white/60 line-through' : 'text-white'}`}>
                      {item.title}
                    </div>
                    {item.description && (
                      <div className="text-sm text-white/60 mt-1">{item.description}</div>
                    )}
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* Evidence Gallery */}
      {photos.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-2xl font-bold text-white">📸 Evidence Gallery</h2>
          {/* Category filter tabs */}
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-xs text-white/50 mr-1">Filter:</span>
            {(['all', 'before', 'during', 'after'] as const).map((tab) => {
              const count =
                tab === 'all'
                  ? photos.length
                  : tab === 'before'
                  ? beforeCount
                  : tab === 'during'
                  ? duringCount
                  : afterCount
              return (
                <button
                  key={tab}
                  type="button"
                  onClick={() => setPhotoFilter(tab)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                    photoFilter === tab
                      ? 'bg-[#F97316] text-black'
                      : 'bg-white/5 border border-white/10 text-white/70 hover:bg-white/10'
                  }`}
                >
                  {tab === 'all' ? 'All' : tab.charAt(0).toUpperCase() + tab.slice(1)} ({count})
                </button>
              )
            })}
          </div>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {filteredPhotos.map((photo) => {
              const cat = effectiveCat(photo)
              return (
                <div
                  key={photo.id}
                  className="bg-white/5 border border-white/10 rounded-xl overflow-hidden cursor-pointer hover:border-white/20 transition-colors relative"
                  onClick={() => {
                    if (photo.url) {
                      setSelectedImage({
                        url: photo.url,
                        alt: photo.description || photo.name,
                      })
                    }
                  }}
                >
                  {/* Category badge with picker */}
                  <div className="absolute top-2 right-2 z-10">
                    <div className="relative">
                      {canEditCategory ? (
                        <>
                          <button
                            type="button"
                            onClick={(e) => {
                              e.stopPropagation()
                              setCategoryDropdownOpen(categoryDropdownOpen === photo.id ? null : photo.id)
                            }}
                            className={`px-2 py-0.5 rounded text-[11px] font-bold uppercase ${categoryBadgeClass(cat)} hover:opacity-90`}
                          >
                            {cat}
                          </button>
                          {categoryDropdownOpen === photo.id && (
                            <>
                              <div className="absolute top-full right-0 mt-1 py-1 min-w-[100px] rounded-lg bg-[#1a1a1a] border border-white/20 shadow-xl z-20">
                                {(['before', 'during', 'after'] as const).map((newCat) => (
                                  <button
                                    key={newCat}
                                    type="button"
                                    onClick={async (e) => {
                                      e.stopPropagation()
                                      await onDocumentCategoryChange?.(photo.id, newCat)
                                      setCategoryDropdownOpen(null)
                                    }}
                                    className="block w-full text-left px-3 py-1.5 text-sm text-white/90 hover:bg-white/10"
                                  >
                                    {newCat.charAt(0).toUpperCase() + newCat.slice(1)}
                                  </button>
                                ))}
                              </div>
                              <div
                                className="fixed inset-0 z-10"
                                aria-hidden
                                onClick={(e) => {
                                  e.stopPropagation()
                                  setCategoryDropdownOpen(null)
                                }}
                              />
                            </>
                          )}
                        </>
                      ) : (
                        <span className={`px-2 py-0.5 rounded text-[11px] font-bold uppercase ${categoryBadgeClass(cat)}`}>
                          {cat}
                        </span>
                      )}
                    </div>
                  </div>
                  {photo.url ? (
                    <div className="relative w-full h-48 overflow-hidden group">
                      <Image
                        src={photo.url}
                        alt={photo.description || photo.name}
                        width={400}
                        height={192}
                        className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                        unoptimized
                      />
                      <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center">
                        <div className="opacity-0 group-hover:opacity-100 transition-opacity">
                          <svg
                            className="w-8 h-8 text-white"
                            fill="none"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeWidth={2}
                              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM10 7v3m0 0v3m0-3h3m-3 0H7"
                            />
                          </svg>
                        </div>
                      </div>
                    </div>
                  ) : (
                    <div className="w-full h-48 bg-white/5 flex items-center justify-center text-white/40">
                      Image unavailable
                    </div>
                  )}
                  <div className="p-3">
                    <div className="text-sm font-semibold text-white">{photo.description || photo.name}</div>
                    {photo.created_at && (
                      <div className="text-xs text-white/60 mt-1">{formatTime(photo.created_at)}</div>
                    )}
                  </div>
                </div>
              )
            })}
          </div>
          {filteredPhotos.length === 0 && photos.length > 0 && (
            <p className="text-center text-white/60 py-6">No photos in this category</p>
          )}
        </div>
      )}

      {/* Team Signatures */}
      {!readOnly && (
        <div className="space-y-4">
          <TeamSignatures jobId={job.id} reportRunId={null} readOnly={readOnly} />
        </div>
      )}

      {/* Activity Timeline */}
      {audit.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-2xl font-bold text-white">🕒 Activity Timeline</h2>
          <div className="bg-white/5 border border-white/10 rounded-xl p-6 space-y-4">
            {audit.slice(0, 20).map((log) => (
              <div key={log.id} className="flex items-start gap-4">
                <div className="w-2 h-2 rounded-full bg-[#F97316] mt-2 flex-shrink-0" />
                <div className="flex-1">
                  <div className="text-sm font-semibold text-white">{formatTime(log.created_at)}</div>
                  <div className="text-white/70 mt-1">{formatAuditEntry(log)}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
    </>
  )
}

