/**
 * Terminology Dictionary
 * 
 * Centralizes all user-facing terminology for the Compliance Ledger product.
 * This allows for consistent language across the UI and enables future
 * vertical-specific terminology (e.g., healthcare vs construction).
 * 
 * Database schema names remain unchanged - this is purely for display.
 */

export const terms = {
  // Core entities
  workRecord: {
    singular: 'Work Record',
    plural: 'Work Records',
    short: 'work record',
    schemaName: 'jobs', // Database table name (not changed)
  },
  
  control: {
    singular: 'Control',
    plural: 'Controls',
    short: 'control',
    schemaName: 'mitigation_items', // Database table name (not changed)
  },
  
  evidence: {
    singular: 'Evidence',
    plural: 'Evidence',
    short: 'evidence',
    schemaName: 'documents', // Database table name (not changed)
  },
  
  attestation: {
    singular: 'Attestation',
    plural: 'Attestations',
    short: 'attestation',
    schemaName: 'job_signoffs', // Database table name (not changed)
  },
  
  operationalContext: {
    singular: 'Operational Context',
    plural: 'Operational Contexts',
    short: 'operational context',
    schemaName: 'sites', // Database table name (not changed)
  },
  
  complianceLedger: {
    singular: 'Compliance Ledger',
    plural: 'Compliance Ledgers',
    short: 'ledger',
    schemaName: 'audit_logs', // Database table name (not changed)
  },
  
  playbook: {
    singular: 'Playbook',
    plural: 'Playbooks',
    short: 'playbook',
    schemaName: 'templates', // Database table name (not changed)
  },
  
  // Actions
  actions: {
    create: 'Create',
    update: 'Update',
    delete: 'Delete',
    view: 'View',
    export: 'Export',
    archive: 'Archive',
    flag: 'Flag',
    unflag: 'Unflag',
    sign: 'Sign',
    verify: 'Verify',
    complete: 'Complete',
    resolve: 'Resolve',
  },
  
  // Status labels
  status: {
    draft: 'Draft',
    inProgress: 'In Progress',
    completed: 'Completed',
    archived: 'Archived',
    cancelled: 'Cancelled',
    onHold: 'On Hold',
    pending: 'Pending',
    signed: 'Signed',
    rejected: 'Rejected',
  },
  
  // Messages
  messages: {
    entryAddedToLedger: 'Entry added to Compliance Ledger',
    ledgerUpdated: 'Ledger updated',
    viewInLedger: 'View in Compliance Ledger',
    auditReady: 'Audit-ready',
    auditNotReady: 'Not audit-ready',
    missingEvidence: 'Missing evidence',
    missingAttestation: 'Missing attestation',
    overdueControl: 'Overdue control',
    roleViolationAttempt: 'Role violation attempt logged',
  },
  
  // Export labels
  exports: {
    ledgerExport: 'Ledger Export',
    controlsReport: 'Controls Report',
    attestationPack: 'Attestation Pack',
    auditPack: 'Audit Pack',
    exportId: 'Export ID',
    generatedBy: 'Generated By',
    generatedAt: 'Generated At',
  },
  
  // Navigation
  navigation: {
    complianceLedger: 'Compliance Ledger',
    workRecords: 'Work Records',
    riskPosture: 'Risk Posture',
    auditReadiness: 'Audit Readiness',
    account: 'Account',
    team: 'Team',
  },
} as const

/**
 * Helper function to get the display term for a schema name
 */
export function getDisplayTerm(schemaName: string, count: number = 1): string {
  for (const [key, value] of Object.entries(terms)) {
    if (typeof value === 'object' && 'schemaName' in value && value.schemaName === schemaName) {
      if ('plural' in value && 'singular' in value) {
        return count === 1 ? value.singular : value.plural
      }
    }
  }
  return schemaName // Fallback to schema name if not found
}

/**
 * Helper function to get schema name from display term
 */
export function getSchemaName(displayTerm: string): string | null {
  for (const [key, value] of Object.entries(terms)) {
    if (typeof value === 'object' && 'schemaName' in value) {
      if (
        value.singular === displayTerm ||
        value.plural === displayTerm ||
        value.short === displayTerm.toLowerCase()
      ) {
        return value.schemaName
      }
    }
  }
  return null
}

