#!/bin/bash

# RiskMate User & Organization Sync Verification Script
# Verifies that web and iOS use the same user.id and organization_id

set -e

echo "🔍 RiskMate User & Organization Sync Verification"
echo "=================================================="
echo ""
echo "This script helps verify that web and iOS are using the same:"
echo "1. User ID (auth.users.id)"
echo "2. Organization ID (users.organization_id)"
echo ""
echo "⚠️  Manual Steps Required:"
echo ""
echo "Step 1: Log in on WEB and run this in browser console:"
echo "----------------------------------------"
echo "const { data: { user } } = await supabase.auth.getUser()"
echo "const { data: userRow } = await supabase.from('users').select('organization_id, role').eq('id', user.id).single()"
echo "console.log('Web User ID:', user.id)"
echo "console.log('Web Email:', user.email)"
echo "console.log('Web Org ID:', userRow?.organization_id)"
echo "console.log('Web Role:', userRow?.role)"
echo "----------------------------------------"
echo ""
echo "Step 2: Log in on iOS and add temporary debug code:"
echo "----------------------------------------"
echo "In your iOS app, add this to the view that loads after login:"
echo ""
echo "if let user = try? await supabase.auth.user {"
echo "    let userRow = try? await supabase"
echo "        .from(\"users\")"
echo "        .select(\"organization_id, role\")"
echo "        .eq(\"id\", user.id)"
echo "        .single()"
echo "        .execute()"
echo "    "
echo "    print(\"iOS User ID: \\(user.id)\")"
echo "    print(\"iOS Email: \\(user.email)\")"
echo "    print(\"iOS Org ID: \\(userRow?.data.organization_id ?? \"nil\")\")"
echo "    print(\"iOS Role: \\(userRow?.data.role ?? \"nil\")\")"
echo "}"
echo "----------------------------------------"
echo ""
echo "Step 3: Compare the values"
echo "----------------------------------------"
echo "✅ PASS: user.id matches on both platforms"
echo "✅ PASS: organization_id matches on both platforms"
echo ""
echo "❌ FAIL: If user.id differs → Different accounts (check email/provider)"
echo "❌ FAIL: If organization_id differs → Different org context"
echo ""
echo "Step 4: Test RLS (Row-Level Security)"
echo "----------------------------------------"
echo "1. Create a job on WEB"
echo "2. Note the job ID"
echo "3. Open jobs list on iOS"
echo "4. Check if the job appears"
echo ""
echo "✅ PASS: Job appears on iOS"
echo "❌ FAIL: Job doesn't appear → RLS blocking or different org_id"
echo ""
echo "For detailed troubleshooting, see DATA_SYNC_VERIFICATION.md"
echo ""
